import React from 'react';
import {AbsoluteFill, useCurrentFrame, interpolate, Video, staticFile} from 'remotion';
import {z} from 'zod';

export const captionedClipSchema = z.object({
  videoSrc: z.string().optional().describe('Path/URL to a video file. For demo, defaults to a placeholder.'),
  title: z.string().optional(),
  captions: z
    .array(
      z.object({
        start: z.number().describe('Start frame'),
        end: z.number().describe('End frame'),
        text: z.string(),
      })
    )
    .optional()
    .describe('Caption segments in frames. (Whisper alignment can be added later).'),
});

export const defaultCaptionedClipProps = {
  videoSrc: undefined,
  title: 'Demo captioned clip',
  captions: [
    {start: 15, end: 90, text: 'Turn raw clips into branded shorts.'},
    {start: 95, end: 170, text: 'Captions are data-driven (frames).'},
    {start: 175, end: 260, text: 'Next: whisper → word timestamps → captions.'},
  ],
};

type Props = z.infer<typeof captionedClipSchema>;

export const CaptionedClip: React.FC<Props> = ({videoSrc, title, captions}) => {
  const frame = useCurrentFrame();

  const active = (captions || []).find((c) => frame >= c.start && frame <= c.end);
  const opacity = active
    ? interpolate(frame, [active.start, active.start + 8, active.end - 8, active.end], [0, 1, 1, 0], {
        extrapolateLeft: 'clamp',
        extrapolateRight: 'clamp',
      })
    : 0;

  return (
    <AbsoluteFill style={{backgroundColor: '#0b1220', color: 'white', fontFamily: 'Inter, system-ui, sans-serif'}}>
      {/* Background video (optional) */}
      <AbsoluteFill style={{opacity: 0.9}}>
        <Video src={videoSrc ?? staticFile('placeholder.mp4')} />
      </AbsoluteFill>

      {/* Top gradient */}
      <AbsoluteFill
        style={{
          background: 'linear-gradient(180deg, rgba(0,0,0,0.75) 0%, rgba(0,0,0,0) 40%)',
        }}
      />

      <div style={{position: 'absolute', top: 60, left: 60, right: 60, fontSize: 44, fontWeight: 700}}>
        {title}
      </div>

      {/* Caption */}
      <div
        style={{
          position: 'absolute',
          left: 80,
          right: 80,
          bottom: 220,
          fontSize: 64,
          fontWeight: 800,
          lineHeight: 1.05,
          textShadow: '0 6px 30px rgba(0,0,0,0.65)',
          opacity,
        }}
      >
        {active?.text ?? ''}
      </div>

      {/* Footer badge */}
      <div
        style={{
          position: 'absolute',
          left: 80,
          bottom: 140,
          padding: '14px 18px',
          borderRadius: 14,
          background: 'rgba(0,0,0,0.55)',
          fontSize: 26,
          fontWeight: 600,
        }}
      >
        Generated by Genie + Remotion
      </div>
    </AbsoluteFill>
  );
};
